### ISSUE TITLE
babel parse import statement error: Unexpected token

### ISSUE THREAD

**Issue by tjx666** [wix/vscode-glean#109]
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

```
  ERR Unexpected token (3:9)
  1 | /* @babel/template */;
  2 | 
> 3 | import { 
    |         ^: SyntaxError: Unexpected token (3:9)
  1 | /* @babel/template */;
  2 | 
> 3 | import { 
    |         ^
	at _class.raise (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:3939:15)
	at _class.unexpected (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:5248:16)
	at _class.parseIdentifierName (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7021:18)
	at _class.parseIdentifier (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7003:21)
	at _class.parseImportSpecifier (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:8472:31)
	at _class.parseImportSpecifiers (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:8466:12)
	at _class.parseImport (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:8417:12)
	at _class.parseImport (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:9860:48)
	at _class.parseStatementContent (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7226:27)
	at _class.parseStatementContent (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:9916:58)
	at _class.parseStatement (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7145:17)
	at _class.parseBlockOrModuleBlockBody (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7696:23)
	at _class.parseBlockBody (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7683:10)
	at _class.parseTopLevel (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7110:10)
	at _class.parse (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:8510:17)
	at parse (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:10465:38)
	at parseWithCodeFrame (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\parse.js:145:32)
	at parseAndBuildMetadata (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\parse.js:43:15)
	at c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\string.js:21:50
	at Function.ast (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\builder.js:47:155)
	at Object.exports.templateToAst (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\out\parsing.js:22:52)
	at Object.isStatelessComp (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\out\modules\statless-to-stateful.js:20:27)
	at CompleteActionProvider.provideCodeActions (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\out\extension.js:30:36)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:586:864
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:345
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:317)
	at T.provideCodeActions (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:586:835)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:631
	at V._withAdapter (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:604:832)
	at V.$provideCodeActions (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:609)
	at p._doInvokeHandler (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:464)
	at p._invokeHandler (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:156)
	at p._receiveRequest (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:766)
	at p._receiveOneMessage (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:623)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:791
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:851:104
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at t.PersistentProtocol._receiveMessage (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:717)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:897
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at p.acceptChunk (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:897)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:249
	at Socket.t (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:197:232)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by borislit** [comment]
Hi @tjx666 . Can you provide more info?
What did u try to do? Have u tried refactoring? Can you provide  a snippet?

**Comment by tjx666** [comment]
whenever I open this file:

![screenshot_2020-03-14_19-35-41](https://user-images.githubusercontent.com/41773861/76681183-1c247680-662b-11ea-962c-e4a0ad6483b0.png)

conent:
```typescript
import { configureStore, Action } from '@reduxjs/toolkit';
import { ThunkAction } from 'redux-thunk';
import rootReducer, { RootState as TempRootState } from 'reducers';

const store = configureStore({
    reducer: rootReducer,
});
export default store;

if (process.env.NODE_ENV === 'development' && module.hot) {
    module.hot.accept('./reducers', () => {
        // eslint-disable-next-line global-require
        const newRootReducer = require('./reducers').default;
        store.replaceReducer(newRootReducer);
    });
}

export type AppDispatch = typeof store.dispatch;
export type RootState = TempRootState;
export type AppThunk = ThunkAction<void, RootState, unknown, Action<string>>;
```

complete error message:

```
 ERR Unexpected token, expected ";" (2:3)
  1 | /* @babel/template */;
> 2 | rt { configureStore, Action } from '@reduxjs/toolkit';
    |   ^
  3 | import { ThunkAction } from 'redux-thunk';
  4 | import rootReducer, { RootState as TempRootState } from 'reducers';
  5 | : SyntaxError: Unexpected token, expected ";" (2:3)
  1 | /* @babel/template */;
> 2 | rt { configureStore, Action } from '@reduxjs/toolkit';
    |   ^
  3 | import { ThunkAction } from 'redux-thunk';
  4 | import rootReducer, { RootState as TempRootState } from 'reducers';
  5 | 
	at _class.raise (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:3939:15)
	at _class.unexpected (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:5248:16)
	at _class.semicolon (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:5232:40)
	at _class.parseExpressionStatement (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7665:10)
	at _class.parseExpressionStatement (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:9980:69)
	at _class.parseStatementContent (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7264:19)
	at _class.parseStatementContent (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:9916:58)
	at _class.parseStatement (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7145:17)
	at _class.parseBlockOrModuleBlockBody (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7696:23)
	at _class.parseBlockBody (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7683:10)
	at _class.parseTopLevel (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:7110:10)
	at _class.parse (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:8510:17)
	at parse (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\parser\lib\index.js:10465:38)
	at parseWithCodeFrame (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\parse.js:145:32)
	at parseAndBuildMetadata (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\parse.js:43:15)
	at c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\string.js:21:50
	at Function.ast (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\node_modules\@babel\template\lib\builder.js:47:155)
	at Object.exports.templateToAst (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\out\parsing.js:22:52)
	at Object.isStatelessComp (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\out\modules\statless-to-stateful.js:20:27)
	at CompleteActionProvider.provideCodeActions (c:\Users\YuTengjing\.vscode\extensions\wix.glean-4.20.0\out\extension.js:30:36)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:586:864
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:345
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:317)
	at T.provideCodeActions (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:586:835)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:631
	at V._withAdapter (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:604:832)
	at V.$provideCodeActions (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:609:609)
	at p._doInvokeHandler (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:464)
	at p._invokeHandler (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:156)
	at p._receiveRequest (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:766)
	at p._receiveOneMessage (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:623)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:791
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:851:104
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at t.PersistentProtocol._receiveMessage (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:717)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:897
	at l.fire (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at p.acceptChunk (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:897)
	at c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:249
	at Socket.t (c:\applications\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:197:232)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
