### ISSUE TITLE
Can't extract component in .tsx file

### ISSUE THREAD

**Issue by rangedsp** [wix/vscode-glean#49]
### OS: 
Windows 10 Pro 1809

### glean:
4.2.3

### VS Code:
1.30.1 (user setup)

### Scaffolded via:
create-react-app with the new typescript option.

### Code (inside `class extends React.Component<any, IState>`):
```
<button
  className={"search-button"}
  type="submit"
  disabled={submitting}
/>
```

### Popup error:
`Maximum call stack size exceeded`

### Console error:
```
ERR Cannot read property 'superClass' of undefined: TypeError: Cannot read property 'superClass' of undefined
    at isSupportedComponent (C:\Users\oO\.vscode\extensions\wix.glean-4.2.3\out\modules\jsx.js:152:28)
    at Object.isStatefulComp (C:\Users\oO\.vscode\extensions\wix.glean-4.2.3\out\modules\jsx.js:158:9)
    at CompleteActionProvider.provideCodeActions (C:\Users\oO\.vscode\extensions\wix.glean-4.2.3\out\extension.js:33:19)
    at c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:556:20
    at t.asThenable (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:141:941)
    at new Promise (<anonymous>)
    at Object.t.asThenable (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:141:909)
    at e.provideCodeActions (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:555:1003)
    at c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:572:308
    at e._withAdapter (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:567:513)
    at e.$provideCodeActions (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:572:270)
    at t._doInvokeHandler (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:837)
    at t._invokeHandler (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:509)
    at t._receiveRequest (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:60)
    at t._receiveOneMessage (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:59)
    at c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:895
    at c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:130:793
    at e.fire (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
    at a (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (c:\Users\oO\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by borislit** [comment]
Hey @rangedsp , thank for reporting! 
Can you post whole original component?

**Comment by lexycole** [comment]
Hello vscode-glean team, my vscode is not showing options for 'convert to functional Component'

**Comment by rangedsp** [comment]
> Hey @rangedsp , thank for reporting!
> Can you post whole original component?

My apologies I completely forgotten to respond to this. I've tried this just now and it's working on latest version of everything. Going to close this issue

**Comment by rangedsp** [comment]
> Hello vscode-glean team, my vscode is not showing options for 'convert to functional Component'

Hey @lexycole you should open a new issue as that sounds like something unrelated to mine

**Comment by lexycole** [comment]
Alright
